name: resource

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Validate

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Enable resources
        run: |
          rm .github/frictionless.yaml
          mv data/valid.json data/valid.resource.json
          mv data/invalid.json data/invalid.resource.json
      - name: Validate data
        uses: frictionlessdata/repository@v1
